version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://username:password@postgresql:5432/stuart-challenge
    ports:
      - "3000:3000"
    command: npm run api:prod
    depends_on:
      postgresql:
        condition: service_healthy
  postgresql:
    image: postgres:15.3
    environment:
      PGUSER: postgres
      POSTGRES_DB: stuart-challenge
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pgdata: {}
